title: Econome.
logo: /assets/img/page2.png
description: 경제학 블로그.
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Youtube
    icon: <i class="fa-brands fa-youtube"></i>
    link: https://www.youtube.com/@portalife_0
  - name: X(Twitter)
    icon: <i class="fa-brands fa-x-twitter"></i>
    link: https://x.com/portalife12
  - name: School
    icon: <i class="fa-solid fa-graduation-cap"></i>
    link: https://www.skku.edu/skku/index.do

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]

imagemagick:
  enabled: true # enables responsive images for your site (recomended, see https://github.com/alshedivat/al-folio/issues/537)
